name: Compile LaTeX Document

on:
  push:
    paths:
      - 'latex/**'
      - '.github/workflows/compile-tex.yml'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install TeX Live and latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Compile LaTeX document
        working-directory: ./latex
        run: latexmk -pdf -interaction=nonstopmode main.tex

      - name: Commit PDF file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add main.pdf
          git commit -m "Update compiled PDF from LaTeX source [skip ci]"
          git push
